 
using System.Web.Mvc;
using System.Web.Mvc.Html;
namespace CodeCampServer.UI
{
//Warning.. This file is automatically generated by the TT template. 
//DO NOT EDIT THIS FILE.  You have been Warned!
	public static class PartialViews
	{
		public static class Shared
		{
			public const string AdminMenu = "AdminMenu";
			public const string DeleteSessionLink = "DeleteSessionLink";
			public const string DeleteSpeakerLink = "DeleteSpeakerLink";
			public const string DeleteTimeSlotLink = "DeleteTimeSlotLink";
			public const string EditSessionLink = "EditSessionLink";
			public const string EditSpeakerLink = "EditSpeakerLink";
			public const string EditTimeSlotLink = "EditTimeSlotLink";
			public const string EditTrackLink = "EditTrackLink";
			public const string Empty = "Empty";
			public const string http404 = "http404";
			public const string Menu = "Menu";
		}
	}

}

